### ISSUE TITLE
Replace script tag to html <head> and use defer attribute for script tag

### ISSUE THREAD

**Issue by VadimsMalickis** [kkozemjakins/Vizitikarte#1]
https://github.com/kkozemjakins/Vizitikarte/blob/d8f2eaec2eda8cd6a3aacb4037c932c0d3f7dbd2/index.html#L25

example:

<head>
    <script src="somesrc.js" defer></script>
</head>

**Comment by kkozemjakins** [comment]
izlaboja kļūdu
